image: debian:bullseye

stages:
  - build
  - test
  - deploy

test-basic:
  stage: test
  before_script:
    - apt-get --allow-releaseinfo-change update && apt-get install -y --no-install-recommends git build-essential sudo
    - ./.github/scripts/setup-environment.sh
    - apt-get install -y imagemagick
    - git submodule update --init --recursive
    - mkdir out
  script:
    - make test CONFIG_FILE=examples/configs/config_zvb.json
    - mv out.png out.rgba out/
  artifacts:
    paths:
      - out/

test-cocotb:
  stage: test
  before_script:
    - apt-get --allow-releaseinfo-change update && apt-get install -y --no-install-recommends git build-essential sudo imagemagick
    - ./.github/scripts/setup-environment.sh
    - apt-get install -y imagemagick
    - git submodule update --init --recursive
    - mkdir out
  script:
    - pip3 install -r cocotb-tests/requirements.txt
    - make cocotb_test CONFIG_FILE=examples/configs/config_zvb.json
    - mv cocotb-tests/sim_build/AIGTop.fst out/
  artifacts:
    paths:
      - out/
  only:
    - merge_requests

build-docs:
  stage: build
  script:
    - apt-get --allow-releaseinfo-change update && apt-get install -y --no-install-recommends git build-essential sudo
    - sudo apt-get install -y --no-install-recommends make python3 python3-pip
    - pip3 install -r docs/requirements.txt
    - SPHINXOPTS="-A conf_py_path=$DOCS_DIR/$SOURCEDIR/ -A commit=$CI_BUILD_REF -A branch=$CI_BUILD_REF_NAME" make html
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - build
      - $CI_DOCS_ARCHIVE

deploy-docs:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build-docs
  stage: deploy
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
