name: build-and-test-design

on: [push]

jobs:
  cocotb_test:
    name: Run Cocotb test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup environment
        run: |
          ./.github/scripts/setup-environment.sh
          pip3 install -r cocotb-tests/requirements.txt

      - name: Run Cocotb test
        run: make cocotb_test CONFIG_FILE=examples/configs/config_zvb.json