name: build-and-test-design

on: [push]

jobs:
  cocotb_test:
    name: Run Cocotb test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt --allow-releaseinfo-change update && sudo apt install -y --no-install-recommends apt-transport-https curl gnupg graphicsmagick-imagemagick-compat default-jdk default-jre
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt update && sudo apt install -y sbt iverilog verilator imagemagick
          pip3 install -r requirements.txt

      - name: Run Cocotb test
        run: make cocotb_test CONFIG_FILE=examples/configs/config_zvb.json

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update -qq
          sudo apt install -y make python3 python3-pip
          pip3 install -r requirements.txt

      - name: Build the documentation
        run: |
          SPHINXOPTS="-A conf_py_path=$DOCS_DIR/$SOURCEDIR/ -A commit=$CI_BUILD_REF -A branch=$CI_BUILD_REF_NAME" make html
          cp docs/*.png build/html

      - name: "Upload artifact: Sphinx HTML"
        uses: actions/upload-artifact@v3
        with:
          name: Documentation-HTML
          path: build/html

      - name: Publish site to GitHub Pages
        if: github.event_name != 'pull_request'
        run: |
          cd build/html
          touch .nojekyll
          git init
          cp ../../.git/config ./.git/config
          git add .
          git config --local user.email "BuildTheDocs@GitHubActions"
          git config --local user.name "GitHub Actions"
          git commit -a -m "update ${{ github.sha }}"
          git push -u origin +HEAD:gh-pages
